# This yaml pipeline will deploy Web App
trigger: none

name: Create Web App
workspace:
  clean: all

pool:
  vmImage: "windows-2019"

parameters:
  - name: azureSubscription
    type: string
    displayName: Service Connection name (Azure)
    default: amitabhdas-azure
  - name: resourceGroupName
    type: string
    displayName: Resourcegroup name for the Web App
    default: RGCloud
  - name: webAppName
    type: string
    displayName: Web app name
    default: mydemoapp
  - name: location
    type: string
    displayName: Location for Web App
    default: eastus2
  - name: appServicePlanSku
    type: string
    displayName: AppServicePlanSku type (ex- 'Free', 'Shared', 'Basic', 'Standard', 'Premium', 'Dynamic')
    default: Standard
  - name: appServicePlanSkuCode
    type: string
    displayName: AppServicePlanSkuCode type (ex- "F1", "D1", "B1", "B2", "B3",  "S1",  "S2",  "S3",  "P1", "P2",  "P3",  "P1V2", "P2V2", "P3V2", "Y1")
    default: S2

steps:
- task: AzurePowerShell@5
  displayName: create - Web APP
  condition: succeeded()
  inputs:
    azureSubscription: ${{parameters.azureSubscription }}
    ScriptType: 'FilePath'
    ScriptPath: 'Scripts/Create-WebApp.ps1'
    ScriptArguments:  -ResourceGroupName ${{parameters.resourceGroupName }}
             -WebAppName '${{parameters.WebAppName }}'
             -Location '${{parameters.location }}'
             -AppServicePlanSku '${{parameters.appServicePlanSku }}'
             -AppServicePlanSkuCode '${{parameters.appServicePlanSkuCode }}'
    azurePowerShellVersion: 'LatestVersion'